#!/usr/bin/python3

from sys import argv;

if (len(argv) == 6):
  if (argv[5] != "-f"):
    if (input("Are you sure?: ").upper() != "Y"):
      exit(0);
else:
  if (input("Are you sure?: ").upper() != "Y"):
    exit(0);

with open("./memory/mem.dat", "w") as fl:
  fl.write("\0"*int(argv[1]));

with open("./memory/memd.dat", "w") as fl:
  fl.write("\0"*int(argv[2]));

with open("./memory/memc.dat", "w") as fl:
  fl.write("\0"*int(argv[3]));

with open("./memory/memsd.dat", "w") as fl:
  fl.write("\0"*int(argv[4]));

