#!/usr/bin/python3
# A program to put files into the virtual drive

import sys;
from govnocodeuc import *;

if (len(sys.argv) != 3):
	print(f"\x1B[31mError! Expected 2 arguments, got {len(sys.argv)-1}. Exiting...\x1B[0m");
	sys.exit(0);
drive = sys.argv[1];
dirnm = sys.argv[2];

GC_EOF = 0x42;

with open(f"./memory/{drive}/mem.dat", "rb") as fl:
	flc = list(fl.read());

for i,j in enumerate(flc):
	if (j == GC_EOF):
		break;

flc[i] = 0x01;
flc[i+1] = 0x03;
i += 2;
for j,k in enumerate(dirnm):
	flc[i+j] = unicodeToGovnocodeDir(k)[0];
i = i+j+1;
flc[i] = 0x01;
flc[i+1] = GC_EOF;

with open(f"./memory/{drive}/mem.dat", "wb") as fl:
	fl.write("".join(map(chr, flc)).encode());
